### ISSUE TITLE
package name or bundle id

### ISSUE THREAD

**Issue by mohamedriadhzrig** [xushihai/VLC-Android#1]
Hi xushihai,did you figure out how to change the bundle id(package name) of the VLC project?

**Comment by xushihai** [comment]
you can change applicationId field at vlc–android/build.gradle

**Comment by mohamedriadhzrig** [comment]
Thank you Xushihai,I tried everything but not that simple solution,Any help with this project?

**Comment by xushihai** [comment]
You can change applicationId if you need
